### ISSUE TITLE
Please add link to the source and/or docs for each returned result.

### ISSUE THREAD

**Issue by budparr** [winkerVSbecks/tachyons-tldr#1]
as per Slack conversation. posting here to track.

**Comment by winkerVSbecks** [comment]
@budparr Is there a way to dynamically generate links based on class name? I'm assuming you meant linking to the appropriate section. For example: `.f1` ➡️ http://tachyons.io/docs/typography/scale/

**Comment by budparr** [comment]
That is what I meant. At a glance, it looks like this might work, (from another [cheatsheet](https://github.com/roperzh/tachyons-cheatsheet/blob/e9d50e871fd6f993ce4ee5a2bc9ff96de8a7da51/app/js/components/search-results.js#L18)):
```
{`https://github.com/tachyons-css/tachyons/blob/master/src/_${src}.css`}
```

**Comment by winkerVSbecks** [comment]
Awesome. That should work. Thanks
