### ISSUE TITLE
Vue routes don't work when navigating directory to them or refreshing the browser

### ISSUE THREAD

**Issue by winkerVSbecks** [winkerVSbecks/tachyons-tldr#3]

**Comment by mastilver** [comment]
How are you hosting it?

Common way to solve that, is to return `index.html` on `404`s

**Comment by winkerVSbecks** [comment]
It's a static deployment on `now.sh` so I don't have control over the sever. I switched to hash location strategy for now. I'll add a proper server with SSR later.

**Comment by mastilver** [comment]
You could use your own express server but yeah, hash location works 👍
